### PR TITLE
Integration tests

### PR DESCRIPTION
**Pull request by Timowest12**
In this PR: created integration tests for following functionalitys

**Login page:**

 - I can see the username and password inputs and the "Submit" button.
 - When I click the submit button without filling in the username and the password, I get a detailed error.
 - When I click the submit button after filling in the username and the password with incorrect data, I get a detailed error.
 - When I click the submit button after filling in the username and the password with correct data, I am redirected to the root page.

**User index page:**

 - I can see the username of all other users.
 - I can see the profile picture for each user.
 - I can see the number of posts each user has written.
 - When I click on a user, I am redirected to that user's show page.

**user show page:**

 - I can see the user's profile picture.
 - I can see the user's username.
 - I can see the number of posts the user has written.
 - I can see the user's bio.
 - I can see the user's first 3 posts.
 - I can see a button that lets me view all of a user's posts.
 - When I click a user's post, it redirects me to that post's show page.
 - When I click to see all posts, it redirects me to the user's post's index page.

**User post index page:**

 - I can see the user's profile picture.
 - I can see the user's username.
 - I can see the number of posts the user has written.
 - I can see a post's title.
 - I can see some of the post's body.
 - I can see the first comments on a post.
 - I can see how many comments a post has.
 - I can see how many likes a post has.
 - I can see a section for pagination if there are more posts than fit on the view.
 - When I click on a post, it redirects me to that post's show page.

**Post show page:**

 - I can see the post's title.
 - I can see who wrote the post.
 - I can see how many comments it has.
 - I can see how many likes it has.
 - I can see the post body.
 - I can see the username of each commenter.
 - I can see the comment each commentor left.

### CODE REVIEW

**Review by andersonlebon — CHANGES_REQUESTED** [review]
### Hi @Timowest12 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

almost-there
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️
- [ ] Kindly note that none of the test is passing. Fix them kindly


image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Timowest12** [comment]
hello @andersonlebon ,
I don't understand why the tests fail on your end, all the tests pass when I run them:
tests passing
I've also restarted my system and had a friend run them as well to check if it's not my system but it passes correctly on all of them.
I'm not sure whether i should just submit for re-review or something else
greets Timo,

**Comment by andersonlebon** [comment]
Hello @Timowest12  sure I tried more than 5 times but tests were not passing I changes the environment but still the same

**Comment by andersonlebon** [comment]
Hey @Timowest12  I have tried again after ruining this `bin/rails webpacker:install ` command and only two of them are failing 

image

**Comment by Timowest12** [comment]
@andersonlebon I added user keys to all objects, I think this should be correct right now. I will ask for a re-review, If you could tell me if everything passes right now I would really appreciate it since I can't see it myself.
Greets Timo.

**Comment by andersonlebon** [comment]
@Timowest12  let me retry

**Comment by andersonlebon** [comment]
Hey, @Timowest12  I run now all the tests are passing, However, try to add this :point_right: `bin/rails webpacker:install`  comment in your readme file so that the next reviewers will know how to run your test.  Because without installing the `Webpacker` no test is passing.


image

**Comment by Timowest12** [comment]
@andersonlebon  Thanks a lot, Appreciate it!

**Review by elisha2kyakpo1 — APPROVED** [review]
Hi 👋 team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
